; Find key codes at https://learn.microsoft.com/en-us/windows/win32/inputdev/virtual-key-codes
; Any of them can be set to 0 to disable.
[Keys]
PreviousVanillaSkin = 0x74
NextVanillaSkin = 0x75
PreviousCustomSkin = 0x76
NextCustomSkin = 0x77